# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20170814_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinfo',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
