# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170814_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='number',
            field=models.IntegerField(),
        ),
    ]
