# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20170814_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowinfo',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
